import {
    Zap, Building2, Crown,
    Link2,
} from 'lucide-react';
export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
    // ── 1. Free ─────────────────────────────────────────────────────────────────
    {
        id: 'free',
        name: 'Free',
        tagline: 'Get started for free',
        description: 'Everything you need to shorten links and track basic performance.',
        price: 0,
        period: null,
        icon: Link2,
        planType: ['FREE'],
        // roleMatch: ['FREE'],
        cta: {
            label: 'Current Plan',
            variant: 'secondary',
            action: 'current',
        },
        features: [
            { label: '100 links per month', included: true },
            { label: 'Custom alias / vanity URLs', included: true },
            { label: 'URL editing & deactivation', included: true },
            { label: 'Link expiration & click limits', included: true },
            { label: '1 link collection', included: true },
            { label: 'Link tags & categories', included: false },
            { label: 'QR code generation (PNG & SVG)', included: false },
            { label: 'Dynamic QR codes', included: false },
            { label: 'Basic analytics (7-day history)', included: false },
            { label: 'Geo, device & browser breakdown', included: false },
            { label: 'API access', included: false },
            { label: 'Password-protected links', included: false },
            { label: 'Bulk link creation', included: false },
            { label: 'Real-time analytics', included: false },
            { label: 'CSV data export', included: false },
            { label: 'Branded QR codes', included: false },
            { label: 'Device & geo-based redirects', included: false },
            { label: 'A/B testing & traffic routing', included: false },
        ],
    },

    // ── 2. Pro Monthly ──────────────────────────────────────────────────────────
    {
        id: 'pro_monthly',
        name: 'Pro',
        tagline: 'Monthly billing',
        description: 'Advanced features for teams and professionals who need full control.',
        price: 9,
        period: 'month',
        icon: Zap,
        planType: ['PRO'],
        // roleMatch: [],           // PREMIUM users default to pro_yearly in the UI
        cta: {
            label: 'Upgrade',
            variant: 'outline',
            action: 'upgrade',
        },
        features: [
            { label: 'Unlimited links', included: true },
            { label: 'Custom alias / vanity URLs', included: true },
            { label: 'URL editing & deactivation', included: true },
            { label: 'Link expiration & click limits', included: true },
            { label: '20 link collections', included: true },
            { label: 'Link tags & categories', included: true },
            { label: 'QR code generation (PNG & SVG)', included: true },
            { label: 'Dynamic QR codes', included: true },
            { label: 'Branded QR codes (logo & custom colors)', included: true },
            { label: 'Advanced analytics (90-day history)', included: true },
            { label: 'Real-time analytics', included: true },
            { label: 'CSV data export', included: true },
            { label: 'Password-protected links', included: true },
            { label: 'Bulk link creation (up to 500/batch)', included: true },
            { label: 'API access (60 req/min)', included: true },
            { label: 'Device & geo-based redirects', included: true },
            { label: 'A/B testing & traffic routing', included: true },
            { label: 'Priority email support', included: true },
        ],
    },

    // // ── 3. Pro Yearly ───────────────────────────────────────────────────────────
    // {
    //     id: 'pro_yearly',
    //     name: 'Pro',
    //     tagline: 'Yearly billing',
    //     description: 'All Pro features at the best price — two months free every year.',
    //     price: 90,
    //     period: 'year',
    //     monthlyEquivalent: 7.5,
    //     badge: {
    //         label: 'Most Popular',
    //         variant: 'purple',
    //     },
    //     featured: true,
    //     icon: Crown,
    //     planType: ['PRO'],
    //     // roleMatch: ['PREMIUM'],
    //     cta: {
    //         label: 'Upgrade',
    //         variant: 'primary',
    //         action: 'upgrade',
    //     },
    //     features: [
    //         { label: 'Unlimited links', included: true },
    //         { label: 'Custom alias / vanity URLs', included: true },
    //         { label: 'URL editing & deactivation', included: true },
    //         { label: 'Link expiration & click limits', included: true },
    //         { label: 'Link tags & categories', included: true },
    //         { label: 'Unlimited link collections', included: true },
    //         { label: 'QR code generation (PNG & SVG)', included: true },
    //         { label: 'Dynamic QR codes', included: true },
    //         { label: 'Branded QR codes (logo & custom colors)', included: true },
    //         { label: 'Advanced analytics (120-day history)', included: true },
    //         { label: 'Real-time analytics', included: true },
    //         { label: 'CSV data export', included: true },
    //         { label: 'Password-protected links', included: true },
    //         { label: 'Bulk link creation (up to 1,000/batch)', included: true },
    //         { label: 'API access (100 req/min)', included: true },
    //         { label: 'Device & geo-based redirects', included: true },
    //         { label: 'A/B testing & traffic routing', included: true },
    //         { label: 'Priority email support', included: true },
    //         { label: '2 months free vs monthly billing', included: true, note: 'Save 17%' },
    //     ],
    // },

    // ── 4. Enterprise ───────────────────────────────────────────────────────────
    {
        id: 'enterprise',
        name: 'Enterprise',
        tagline: 'Custom pricing',
        description: 'Tailored solutions for large teams with advanced security and compliance needs.',
        price: null,
        period: null,
        badge: {
            label: 'Custom Pricing',
            variant: 'default',
        },
        icon: Building2,
        planType: ['ENTERPRISE'],
        // roleMatch: ['ADMIN'],
        cta: {
            label: 'Contact Sales',
            variant: 'outline',
            action: 'contact',
        },
        features: [
            { label: 'Everything in Pro Yearly', included: true },
            { label: 'Unlimited team members', included: true },
            { label: 'SSO / SAML authentication', included: true },
            { label: 'Custom short domain (white-label)', included: true },
            { label: 'Dedicated account manager', included: true },
            { label: '99.9% SLA uptime guarantee', included: true },
            { label: 'Custom API rate limits', included: true },
            { label: 'Advanced security controls', included: true },
            { label: 'Custom integrations & webhooks', included: true },
            { label: 'Audit logs & compliance reports', included: true },
            { label: '24/7 priority phone & chat support', included: true },
            { label: 'Volume discounts', included: true },
        ],
    },
];
